- name: Firewall commit
  hosts: PA
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Commit pending firewall changes
    panos_commit:
      provider: '{{ cli }}'

  vars:
    cli:
      ip_address: '{{ inventory_hostname }}'
      username: '{{ ansible_user }}'
      password: '{{ansible_password}}'
